### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by MilanSkocic** [interkosmos/fortran-tcl86#1]
Hi,

I'm a huge fan of tcl/tk for creating GUIs with Fortran and C. I tried your library and it works perfectly for me in my Fortran projects. I wanted to ask you if you consider your code stable enough for production? Do you plan to make a release?

Best regards.

**Comment by interkosmos** [comment]
I consider the library as stable for production. I’ve created a [release](https://github.com/interkosmos/fortran-tcl86/releases/tag/0.1.0) of the current state.

**Comment by MilanSkocic** [comment]
Thanks!
